name: Mod Suggestion
description: Suggest feature ideas for existing mods
title: "[Suggestion]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing your ideas  
  - type: textarea
    id: mod
    attributes:
      label: Target Mod
      placeholder: What mod is this idea for?      
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Your ideas/comments
      placeholder: What would you like to see added?      
    validations:
      required: true